<a href="https://colab.research.google.com/github/RajnandiniG/ML_NLP-TF/blob/main/3.GPT_2%2Cbert.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

**GPT-2**

In [3]:
from transformers import pipeline
import textwrap
wrapper = textwrap.TextWrapper(width=80, break_long_words=False, break_on_hyphens=False)

In [4]:
from transformers import pipeline

generator = pipeline("text-generation", model='gpt2')
sentences = generator('The plane was flying right above')[0]['generated_text']
print('\n')
print(wrapper.fill(sentences))

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.




The plane was flying right above the U.S. consulate in Benghazi, Libya, where
Ambassador Chris Stevens was killed, and an area in the desert known as "Din,"
according to The Associated Press.  A spokesman for the U.


In [5]:
sentences = generator('Town was full of happy people and one day')[0]['generated_text']
print('\n')
print(wrapper.fill(sentences))

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.




Town was full of happy people and one day when they asked what he was doing, he
said he was in prison. But it wasn't at the time that he wanted to be jailed, or
be arrested.  "I just loved my job


**Tokenizers**

In [9]:
from transformers import pipeline
from textwrap import TextWrapper

# Initialize the text generation pipeline
generator = pipeline("text-generation", model='gpt2')
#sentences = generator('The plane was flying right above')[0]['generated_text']

# Set parameters for text generation
max_length = 550  # Maximum number of tokens to generate
num_return_sequences = 1  # Number of sequences to return

# Generate text
generated_text = generator(
    'Town was full of happy people and one day',
    max_length=max_length,
    num_return_sequences=num_return_sequences
)[0]['generated_text']

# Print the generated text with line wrapping
wrapper = TextWrapper(width=70)
print('\n')
print(wrapper.fill(generated_text))

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.




Town was full of happy people and one day they lost a good bit.  The
first thing I noticed was that the park was empty as soon as I entered
it. They were all lined up to go grab pizza, but a couple walked by
and said they would pay for a ride to some other amusement park.  I
didn't notice one last guy as he stood near me while they walked by
and took off holding pizza. When he did arrive, he waved goodbye to
customers. I felt really sad right now. It was just that I didn't like
people and it got to the point that it was time to go get a pizza.
The next day I went to the park and started talking to people about
their experience.  Everyone was amazing and all were smiling and
chatting a great deal. The owner was really nice and there were some
even running around when I got the call.  So one night after the park
closed they decided they would pay half of the ticket price to the
other park. Just like the last time I got to Park Lane I got a $10
tip.  I'll not get into how Park Lane work

In [19]:
%%capture
#magic cmd, any printed output or error messages will not be displayed in the interface
!pip install -q -U tensorflow-text
!pip install -q tf-models-official==2.4.0

In [20]:
!pip install bert

import tensorflow as tf
import tensorflow_hub
import tensorflow_text
from official.nlp import bert
import official.nlp.bert.tokenization
import os

In [21]:
import tensorflow as tf

gs_folder_bert = "gs://cloud-tpu-checkpoints/bert/v3/uncased_L-12_H-768_A-12"
tf.io.gfile.listdir(gs_folder_bert)

['bert_config.json',
 'bert_model.ckpt.data-00000-of-00001',
 'bert_model.ckpt.index',
 'vocab.txt']

In [22]:
tokenizer = bert.tokenization.FullTokenizer(
    vocab_file=os.path.join(gs_folder_bert, "vocab.txt"),
     do_lower_case=True)

print("Vocab size:", len(tokenizer.vocab))

Vocab size: 30522


In [25]:
bert_model_name = 'bert_en_uncased_L-12_H-768_A-12'
tfhub_handle_preprocess = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
bert_preprocess_model = tensorflow_hub.KerasLayer(tfhub_handle_preprocess) #define bert model

In [26]:
sentence = 'Life is full of fairytale'
tokens = tokenizer.tokenize(sentence)
print(tokens)
ids = tokenizer.convert_tokens_to_ids(tokens)
print(ids)

['life', 'is', 'full', 'of', 'fairy', '##tale']
[2166, 2003, 2440, 1997, 8867, 22059]


In [27]:
sentences = ['I believe in miracle',
             'what about you?']
text_preprocessed = bert_preprocess_model(sentences)
text_preprocessed

{'input_word_ids': <tf.Tensor: shape=(2, 128), dtype=int32, numpy=
 array([[ 101, 1045, 2903, 1999, 9727,  102,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0],
        [ 101, 2054, 2055, 2017, 1029,  102,    0,    0,


The output shown above is the result of preprocessing a list of sentences using a BERT preprocessing model. This preprocessing is necessary to convert the text into a format that the BERT model can work with & understand.

In [28]:
text_preprocessed["input_word_ids"].shape

TensorShape([2, 128])

In [29]:
text_preprocessed["input_word_ids"]

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[ 101, 1045, 2903, 1999, 9727,  102,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [ 101, 2054, 2055, 2017, 1029,  102,    0,    0,    0,    0,    0,
           0,

In [30]:
text_preprocessed["input_mask"]

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

**BERT**

In [1]:
%%capture
!pip install -U tensorflow-text
!pip install tf-models-official

In [2]:
import os
import shutil
from pathlib import Path

import tensorflow as tf
import tensorflow_hub
import tensorflow_text as text
from official.nlp import optimization  # to create AdamW optimizer
import datetime

import matplotlib.pyplot as plt

tf.get_logger().setLevel('ERROR')

In [3]:
url = 'https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz'

dataset = tf.keras.utils.get_file('aclImdb_v1.tar.gz', url,
                                  untar=True, cache_dir='.',
                                  cache_subdir='')

dataset_dir = Path('.') / 'aclImdb'
train_dir = Path(dataset_dir) / 'train'
test_dir = Path(dataset_dir) / 'test'

remove_dir = Path(train_dir) / 'unsup'
shutil.rmtree(remove_dir)

AUTOTUNE = tf.data.AUTOTUNE
batch_size = 32
seed = 1

raw_train_ds = tf.keras.preprocessing.text_dataset_from_directory(
    train_dir,
    batch_size=batch_size,
    validation_split=0.2,
    subset='training',
    seed=seed)

class_names = raw_train_ds.class_names
train_ds = raw_train_ds.cache().prefetch(buffer_size=AUTOTUNE)

val_ds = tf.keras.preprocessing.text_dataset_from_directory(
    train_dir,
    batch_size=batch_size,
    validation_split=0.2,
    subset='validation',
    seed=seed)

val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

test_ds = tf.keras.preprocessing.text_dataset_from_directory(
    test_dir,
    batch_size=batch_size)

84125825/84125825 ━━━━━━━━━━━━━━━━━━━━ 34s 0us/step
Found 25000 files belonging to 2 classes.
Using 20000 files for training.
Found 25000 files belonging to 2 classes.
Using 5000 files for validation.
Found 25000 files belonging to 2 classes.


In [4]:
test_ds = test_ds.cache().prefetch(buffer_size=AUTOTUNE)

for text_batch, label_batch in train_ds.take(1):
  for i in range(3):
    print(f'Review: {text_batch.numpy()[i]}')
    label = label_batch.numpy()[i]
    print(f'Label : {label} ({class_names[label]})')

Review: b'Stupid and just plain weird movie about some kid who becomes traumatized when he finds out Santa isn\'t real (???). He grows up and becomes an adult (Brandon Maggart) who makes lists of people who are naughty or nice. One Christmas he snaps and sets out to kill the naughty people--dressed as Santa of course.<br /><br />Boring and just plain bad killer Santa movie. If you\'re looking for gore, it\'s not here. Only a few of the murders are shown and they\'re not that gory with VERY fake effects. Most of the movie just contains Brandon Maggart talking to himself and slowly going crazy. The script is trite, the acting is terrible and it leads to an ending which had me staring slack-jawed at the TV. Seriously, I had to rewind the tape and watch it again to make sure I wasn\'t hallucinating! Really REALLY poor ending.<br /><br />If you want a scary Christmas flick rent "Black Christmas" (the original 70s version---NOT the terrible remake). Avoid this one at all costs.'
Label : 0 (n

In [7]:
tfhub_handle_encoder = 'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2/1' # small BERT model
tfhub_handle_preprocess = 'https://tfhub.dev/tensorflow/bert_en_cased_preprocess/3'
bert_preprocess_model = tensorflow_hub.KerasLayer(tfhub_handle_preprocess)

sentence = ['I believe in miracle']
text_preprocessed = bert_preprocess_model(sentence)

print(f'Shape      : {text_preprocessed["input_word_ids"].shape}')
print(f'Word Ids   : {text_preprocessed["input_word_ids"][0, :12]}')
print(f'Input Mask : {text_preprocessed["input_mask"][0, :12]}')
print(f'Type Ids   : {text_preprocessed["input_type_ids"][0, :12]}')

Shape      : (1, 128)
Word Ids   : [  101   146  2059  1107 14173   102     0     0     0     0     0     0]
Input Mask : [1 1 1 1 1 1 0 0 0 0 0 0]
Type Ids   : [0 0 0 0 0 0 0 0 0 0 0 0]


In [8]:
bert_model = tensorflow_hub.KerasLayer(tfhub_handle_encoder)

bert_results = bert_model(text_preprocessed)

print(f'Loaded BERT: {tfhub_handle_encoder}')
print(f'Pooled Outputs Shape:{bert_results["pooled_output"].shape}')
print(f'Pooled Outputs Values:{bert_results["pooled_output"][0, :12]}')
print(f'Sequence Outputs Shape:{bert_results["sequence_output"].shape}')
print(f'Sequence Outputs Values:{bert_results["sequence_output"][0, :12]}')

Loaded BERT: https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2/1
Pooled Outputs Shape:(1, 128)
Pooled Outputs Values:[-0.9999971  -0.00950873 -0.9993562  -0.09174231 -0.9992305  -0.7214091
 -0.9645414  -0.32689333  0.00905465 -0.005271    0.08149726 -0.11363656]
Sequence Outputs Shape:(1, 128, 128)
Sequence Outputs Values:[[-1.4224595   0.96084493 -3.4544847  ... -1.1071242  -0.06224853
   0.35893947]
 [-2.295921    0.5823561  -0.11846457 ... -1.4824772  -0.64284575
   1.0963805 ]
 [-1.3243483   0.16223559 -0.4040395  ... -2.9923267  -0.46362212
   0.789387  ]
 ...
 [-1.332586    0.5354152  -0.51399684 ... -2.1526566   0.0732574
   0.76045084]
 [-1.3899626   0.85684246 -0.3920994  ... -2.0235286   0.00574119
   0.71734333]
 [-1.3917826   1.2101243  -0.4682099  ... -1.7744002  -0.4967941
   0.50271636]]
